// Generated by `pnpm db:types` from supabase/migrations. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  demomart: {
    Tables: {
      agent_log: {
        Row: {
          created_at: string;
          id: number;
          key_id: string | null;
          method: string;
          path: string;
          reason: string | null;
          request_id: string | null;
          tag: string | null;
          verdict: string;
        };
        Insert: {
          created_at?: string;
          id?: never;
          key_id?: string | null;
          method: string;
          path: string;
          reason?: string | null;
          request_id?: string | null;
          tag?: string | null;
          verdict: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          key_id?: string | null;
          method?: string;
          path?: string;
          reason?: string | null;
          request_id?: string | null;
          tag?: string | null;
          verdict?: string;
        };
        Relationships: [];
      };
      checkout_sessions: {
        Row: {
          agent_key_id: string | null;
          canceled_at: string | null;
          complete_idempotency_key: string | null;
          completed_at: string | null;
          contract_ref: Json | null;
          create_idempotency_key: string | null;
          created_at: string;
          fulfillment_address: Json | null;
          fulfillment_option_id: string | null;
          id: string;
          line_items: NonNullable<Json>;
          messages: NonNullable<Json>;
          status: string;
          totals: NonNullable<Json>;
          updated_at: string;
        };
        Insert: {
          agent_key_id?: string | null;
          canceled_at?: string | null;
          complete_idempotency_key?: string | null;
          completed_at?: string | null;
          contract_ref?: Json | null;
          create_idempotency_key?: string | null;
          created_at?: string;
          fulfillment_address?: Json | null;
          fulfillment_option_id?: string | null;
          id: string;
          line_items?: NonNullable<Json>;
          messages?: NonNullable<Json>;
          status?: string;
          totals?: NonNullable<Json>;
          updated_at?: string;
        };
        Update: {
          agent_key_id?: string | null;
          canceled_at?: string | null;
          complete_idempotency_key?: string | null;
          completed_at?: string | null;
          contract_ref?: Json | null;
          create_idempotency_key?: string | null;
          created_at?: string;
          fulfillment_address?: Json | null;
          fulfillment_option_id?: string | null;
          id?: string;
          line_items?: NonNullable<Json>;
          messages?: NonNullable<Json>;
          status?: string;
          totals?: NonNullable<Json>;
          updated_at?: string;
        };
        Relationships: [];
      };
      listings: {
        Row: {
          id: string;
          injection_text: string | null;
          jsonld_spec: Json | null;
          spec: NonNullable<Json>;
          title: string;
          updated_at: string;
          variant_id: string;
        };
        Insert: {
          id?: string;
          injection_text?: string | null;
          jsonld_spec?: Json | null;
          spec: NonNullable<Json>;
          title: string;
          updated_at?: string;
          variant_id: string;
        };
        Update: {
          id?: string;
          injection_text?: string | null;
          jsonld_spec?: Json | null;
          spec?: NonNullable<Json>;
          title?: string;
          updated_at?: string;
          variant_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "listings_variant_id_fkey";
            columns: ["variant_id"];
            isOneToOne: true;
            referencedRelation: "variants";
            referencedColumns: ["id"];
          },
        ];
      };
      mutation_log: {
        Row: {
          actor: string;
          after: Json | null;
          before: Json | null;
          created_at: string;
          id: number;
          mutation: string;
          scenario: string | null;
          target: NonNullable<Json>;
        };
        Insert: {
          actor?: string;
          after?: Json | null;
          before?: Json | null;
          created_at?: string;
          id?: never;
          mutation: string;
          scenario?: string | null;
          target?: NonNullable<Json>;
        };
        Update: {
          actor?: string;
          after?: Json | null;
          before?: Json | null;
          created_at?: string;
          id?: never;
          mutation?: string;
          scenario?: string | null;
          target?: NonNullable<Json>;
        };
        Relationships: [];
      };
      offers: {
        Row: {
          availability: string;
          currency: string;
          delivery_max_days: number;
          delivery_min_days: number;
          final_sale: boolean;
          id: string;
          listing_id: string;
          pack_size: number;
          price_minor: number;
          return_policy_id: string;
          revision: number;
          seller_id: string;
          stock: number;
          subscription: Json | null;
          updated_at: string;
        };
        Insert: {
          availability?: string;
          currency?: string;
          delivery_max_days: number;
          delivery_min_days: number;
          final_sale?: boolean;
          id: string;
          listing_id: string;
          pack_size?: number;
          price_minor: number;
          return_policy_id: string;
          revision?: number;
          seller_id: string;
          stock?: number;
          subscription?: Json | null;
          updated_at?: string;
        };
        Update: {
          availability?: string;
          currency?: string;
          delivery_max_days?: number;
          delivery_min_days?: number;
          final_sale?: boolean;
          id?: string;
          listing_id?: string;
          pack_size?: number;
          price_minor?: number;
          return_policy_id?: string;
          revision?: number;
          seller_id?: string;
          stock?: number;
          subscription?: Json | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "offers_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: true;
            referencedRelation: "listings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_return_policy_id_fkey";
            columns: ["return_policy_id"];
            isOneToOne: false;
            referencedRelation: "policies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_seller_id_fkey";
            columns: ["seller_id"];
            isOneToOne: false;
            referencedRelation: "sellers";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          checkout_session_id: string;
          contract_verification: Json | null;
          created_at: string;
          currency: string;
          id: string;
          payment: NonNullable<Json>;
          status: string;
          total_minor: number;
          updated_at: string;
        };
        Insert: {
          checkout_session_id: string;
          contract_verification?: Json | null;
          created_at?: string;
          currency?: string;
          id: string;
          payment?: NonNullable<Json>;
          status?: string;
          total_minor: number;
          updated_at?: string;
        };
        Update: {
          checkout_session_id?: string;
          contract_verification?: Json | null;
          created_at?: string;
          currency?: string;
          id?: string;
          payment?: NonNullable<Json>;
          status?: string;
          total_minor?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_checkout_session_id_fkey";
            columns: ["checkout_session_id"];
            isOneToOne: true;
            referencedRelation: "checkout_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      policies: {
        Row: {
          created_at: string;
          id: string;
          kind: string;
          name: string;
          terms: NonNullable<Json>;
        };
        Insert: {
          created_at?: string;
          id: string;
          kind: string;
          name: string;
          terms: NonNullable<Json>;
        };
        Update: {
          created_at?: string;
          id?: string;
          kind?: string;
          name?: string;
          terms?: NonNullable<Json>;
        };
        Relationships: [];
      };
      products: {
        Row: {
          brand: string;
          category: string;
          created_at: string;
          department: string;
          description: string;
          id: string;
          image_path: string | null;
          name: string;
          roles: string[];
          slug: string;
        };
        Insert: {
          brand: string;
          category: string;
          created_at?: string;
          department: string;
          description: string;
          id?: string;
          image_path?: string | null;
          name: string;
          roles?: string[];
          slug: string;
        };
        Update: {
          brand?: string;
          category?: string;
          created_at?: string;
          department?: string;
          description?: string;
          id?: string;
          image_path?: string | null;
          name?: string;
          roles?: string[];
          slug?: string;
        };
        Relationships: [];
      };
      sellers: {
        Row: {
          created_at: string;
          id: string;
          name: string;
        };
        Insert: {
          created_at?: string;
          id: string;
          name: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
        };
        Relationships: [];
      };
      tap_nonces: {
        Row: {
          key_id: string;
          nonce: string;
          seen_at: string;
        };
        Insert: {
          key_id: string;
          nonce: string;
          seen_at?: string;
        };
        Update: {
          key_id?: string;
          nonce?: string;
          seen_at?: string;
        };
        Relationships: [];
      };
      variants: {
        Row: {
          gtin: string;
          id: string;
          mpn: string;
          option_label: string | null;
          product_id: string;
          sku: string;
          sort_order: number;
        };
        Insert: {
          gtin: string;
          id?: string;
          mpn: string;
          option_label?: string | null;
          product_id: string;
          sku: string;
          sort_order?: number;
        };
        Update: {
          gtin?: string;
          id?: string;
          mpn?: string;
          option_label?: string | null;
          product_id?: string;
          sku?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "variants_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      webhook_outbox: {
        Row: {
          attempts: number;
          created_at: string;
          delivered_at: string | null;
          event_id: string;
          event_type: string;
          id: string;
          last_error: string | null;
          next_attempt_at: string;
          order_id: string;
          payload: NonNullable<Json>;
        };
        Insert: {
          attempts?: number;
          created_at?: string;
          delivered_at?: string | null;
          event_id: string;
          event_type: string;
          id?: string;
          last_error?: string | null;
          next_attempt_at?: string;
          order_id: string;
          payload: NonNullable<Json>;
        };
        Update: {
          attempts?: number;
          created_at?: string;
          delivered_at?: string | null;
          event_id?: string;
          event_type?: string;
          id?: string;
          last_error?: string | null;
          next_attempt_at?: string;
          order_id?: string;
          payload?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "webhook_outbox_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      quote: {
        Args: { p_items: Json };
        Returns: {
          merchandise_minor: number;
          shipping_minor: number;
          tax_minor: number;
          total_minor: number;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  demomart: {
    Enums: {},
  },
} as const;
