// Generated by `pnpm db:types` from supabase/migrations. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  greathub: {
    Tables: {
      agent_log: {
        Row: {
          created_at: string;
          id: number;
          key_id: string | null;
          method: string;
          path: string;
          reason: string | null;
          request_id: string | null;
          tag: string | null;
          verdict: string;
        };
        Insert: {
          created_at?: string;
          id?: never;
          key_id?: string | null;
          method: string;
          path: string;
          reason?: string | null;
          request_id?: string | null;
          tag?: string | null;
          verdict: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          key_id?: string | null;
          method?: string;
          path?: string;
          reason?: string | null;
          request_id?: string | null;
          tag?: string | null;
          verdict?: string;
        };
        Relationships: [];
      };
      catalog_baseline: {
        Row: {
          captured_at: string;
          id: boolean;
          listings: NonNullable<Json>;
          offers: NonNullable<Json>;
          policies: NonNullable<Json>;
        };
        Insert: {
          captured_at?: string;
          id?: boolean;
          listings: NonNullable<Json>;
          offers: NonNullable<Json>;
          policies: NonNullable<Json>;
        };
        Update: {
          captured_at?: string;
          id?: boolean;
          listings?: NonNullable<Json>;
          offers?: NonNullable<Json>;
          policies?: NonNullable<Json>;
        };
        Relationships: [];
      };
      checkout_sessions: {
        Row: {
          agent_key_id: string | null;
          buyer: Json | null;
          canceled_at: string | null;
          complete_idempotency_key: string | null;
          completed_at: string | null;
          completing_at: string | null;
          contract_ref: Json | null;
          create_idempotency_key: string | null;
          created_at: string;
          fulfillment_address: Json | null;
          fulfillment_option_id: string | null;
          id: string;
          items: NonNullable<Json>;
          line_items: NonNullable<Json>;
          messages: NonNullable<Json>;
          snapshot: Json | null;
          status: string;
          totals: NonNullable<Json>;
          updated_at: string;
        };
        Insert: {
          agent_key_id?: string | null;
          buyer?: Json | null;
          canceled_at?: string | null;
          complete_idempotency_key?: string | null;
          completed_at?: string | null;
          completing_at?: string | null;
          contract_ref?: Json | null;
          create_idempotency_key?: string | null;
          created_at?: string;
          fulfillment_address?: Json | null;
          fulfillment_option_id?: string | null;
          id: string;
          items?: NonNullable<Json>;
          line_items?: NonNullable<Json>;
          messages?: NonNullable<Json>;
          snapshot?: Json | null;
          status?: string;
          totals?: NonNullable<Json>;
          updated_at?: string;
        };
        Update: {
          agent_key_id?: string | null;
          buyer?: Json | null;
          canceled_at?: string | null;
          complete_idempotency_key?: string | null;
          completed_at?: string | null;
          completing_at?: string | null;
          contract_ref?: Json | null;
          create_idempotency_key?: string | null;
          created_at?: string;
          fulfillment_address?: Json | null;
          fulfillment_option_id?: string | null;
          id?: string;
          items?: NonNullable<Json>;
          line_items?: NonNullable<Json>;
          messages?: NonNullable<Json>;
          snapshot?: Json | null;
          status?: string;
          totals?: NonNullable<Json>;
          updated_at?: string;
        };
        Relationships: [];
      };
      idempotency_keys: {
        Row: {
          created_at: string;
          key: string;
          request_hash: string;
          response: Json | null;
          scope: string;
          status_code: number | null;
        };
        Insert: {
          created_at?: string;
          key: string;
          request_hash: string;
          response?: Json | null;
          scope: string;
          status_code?: number | null;
        };
        Update: {
          created_at?: string;
          key?: string;
          request_hash?: string;
          response?: Json | null;
          scope?: string;
          status_code?: number | null;
        };
        Relationships: [];
      };
      listings: {
        Row: {
          id: string;
          injection_text: string | null;
          jsonld_spec: Json | null;
          spec: NonNullable<Json>;
          title: string;
          updated_at: string;
          variant_id: string;
        };
        Insert: {
          id?: string;
          injection_text?: string | null;
          jsonld_spec?: Json | null;
          spec: NonNullable<Json>;
          title: string;
          updated_at?: string;
          variant_id: string;
        };
        Update: {
          id?: string;
          injection_text?: string | null;
          jsonld_spec?: Json | null;
          spec?: NonNullable<Json>;
          title?: string;
          updated_at?: string;
          variant_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "listings_variant_id_fkey";
            columns: ["variant_id"];
            isOneToOne: true;
            referencedRelation: "variants";
            referencedColumns: ["id"];
          },
        ];
      };
      mock_recalls: {
        Row: {
          hazard: string;
          id: number;
          posted_at: string;
          recall_number: string;
          remedy: string;
          sku: string;
        };
        Insert: {
          hazard: string;
          id?: never;
          posted_at?: string;
          recall_number: string;
          remedy: string;
          sku: string;
        };
        Update: {
          hazard?: string;
          id?: never;
          posted_at?: string;
          recall_number?: string;
          remedy?: string;
          sku?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mock_recalls_sku_fkey";
            columns: ["sku"];
            isOneToOne: false;
            referencedRelation: "variants";
            referencedColumns: ["sku"];
          },
        ];
      };
      mutation_log: {
        Row: {
          actor: string;
          after: Json | null;
          before: Json | null;
          created_at: string;
          id: number;
          mutation: string;
          scenario: string | null;
          target: NonNullable<Json>;
        };
        Insert: {
          actor?: string;
          after?: Json | null;
          before?: Json | null;
          created_at?: string;
          id?: never;
          mutation: string;
          scenario?: string | null;
          target?: NonNullable<Json>;
        };
        Update: {
          actor?: string;
          after?: Json | null;
          before?: Json | null;
          created_at?: string;
          id?: never;
          mutation?: string;
          scenario?: string | null;
          target?: NonNullable<Json>;
        };
        Relationships: [];
      };
      offers: {
        Row: {
          availability: string;
          currency: string;
          delivery_max_days: number;
          delivery_min_days: number;
          final_sale: boolean;
          id: string;
          listing_id: string;
          pack_size: number;
          price_minor: number;
          return_policy_id: string;
          revision: number;
          seller_id: string;
          shipping_fee_minor: number;
          ships_variant_id: string | null;
          stock: number;
          subscription: Json | null;
          updated_at: string;
        };
        Insert: {
          availability?: string;
          currency?: string;
          delivery_max_days: number;
          delivery_min_days: number;
          final_sale?: boolean;
          id: string;
          listing_id: string;
          pack_size?: number;
          price_minor: number;
          return_policy_id: string;
          revision?: number;
          seller_id: string;
          shipping_fee_minor?: number;
          ships_variant_id?: string | null;
          stock?: number;
          subscription?: Json | null;
          updated_at?: string;
        };
        Update: {
          availability?: string;
          currency?: string;
          delivery_max_days?: number;
          delivery_min_days?: number;
          final_sale?: boolean;
          id?: string;
          listing_id?: string;
          pack_size?: number;
          price_minor?: number;
          return_policy_id?: string;
          revision?: number;
          seller_id?: string;
          shipping_fee_minor?: number;
          ships_variant_id?: string | null;
          stock?: number;
          subscription?: Json | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "offers_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: true;
            referencedRelation: "listings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_return_policy_id_fkey";
            columns: ["return_policy_id"];
            isOneToOne: false;
            referencedRelation: "policies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_seller_id_fkey";
            columns: ["seller_id"];
            isOneToOne: false;
            referencedRelation: "sellers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_ships_variant_id_fkey";
            columns: ["ships_variant_id"];
            isOneToOne: false;
            referencedRelation: "variants";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          agent_key_id: string | null;
          buyer: Json | null;
          checkout_session_id: string;
          contract_ref: Json | null;
          contract_verification: Json | null;
          created_at: string;
          currency: string;
          fulfillment_address: Json | null;
          grant_id: string | null;
          id: string;
          line_items: NonNullable<Json>;
          payment: NonNullable<Json>;
          status: string;
          total_minor: number;
          totals: NonNullable<Json>;
          updated_at: string;
        };
        Insert: {
          agent_key_id?: string | null;
          buyer?: Json | null;
          checkout_session_id: string;
          contract_ref?: Json | null;
          contract_verification?: Json | null;
          created_at?: string;
          currency?: string;
          fulfillment_address?: Json | null;
          grant_id?: string | null;
          id: string;
          line_items?: NonNullable<Json>;
          payment?: NonNullable<Json>;
          status?: string;
          total_minor: number;
          totals?: NonNullable<Json>;
          updated_at?: string;
        };
        Update: {
          agent_key_id?: string | null;
          buyer?: Json | null;
          checkout_session_id?: string;
          contract_ref?: Json | null;
          contract_verification?: Json | null;
          created_at?: string;
          currency?: string;
          fulfillment_address?: Json | null;
          grant_id?: string | null;
          id?: string;
          line_items?: NonNullable<Json>;
          payment?: NonNullable<Json>;
          status?: string;
          total_minor?: number;
          totals?: NonNullable<Json>;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_checkout_session_id_fkey";
            columns: ["checkout_session_id"];
            isOneToOne: true;
            referencedRelation: "checkout_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      policies: {
        Row: {
          created_at: string;
          id: string;
          kind: string;
          name: string;
          terms: NonNullable<Json>;
        };
        Insert: {
          created_at?: string;
          id: string;
          kind: string;
          name: string;
          terms: NonNullable<Json>;
        };
        Update: {
          created_at?: string;
          id?: string;
          kind?: string;
          name?: string;
          terms?: NonNullable<Json>;
        };
        Relationships: [];
      };
      products: {
        Row: {
          brand: string;
          category: string;
          created_at: string;
          department: string;
          description: string;
          id: string;
          image_path: string | null;
          name: string;
          roles: string[];
          slug: string;
        };
        Insert: {
          brand: string;
          category: string;
          created_at?: string;
          department: string;
          description: string;
          id?: string;
          image_path?: string | null;
          name: string;
          roles?: string[];
          slug: string;
        };
        Update: {
          brand?: string;
          category?: string;
          created_at?: string;
          department?: string;
          description?: string;
          id?: string;
          image_path?: string | null;
          name?: string;
          roles?: string[];
          slug?: string;
        };
        Relationships: [];
      };
      sellers: {
        Row: {
          created_at: string;
          id: string;
          name: string;
        };
        Insert: {
          created_at?: string;
          id: string;
          name: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
        };
        Relationships: [];
      };
      tap_nonces: {
        Row: {
          key_id: string;
          nonce: string;
          seen_at: string;
        };
        Insert: {
          key_id: string;
          nonce: string;
          seen_at?: string;
        };
        Update: {
          key_id?: string;
          nonce?: string;
          seen_at?: string;
        };
        Relationships: [];
      };
      variants: {
        Row: {
          gtin: string;
          id: string;
          mpn: string;
          option_label: string | null;
          product_id: string;
          sku: string;
          sort_order: number;
        };
        Insert: {
          gtin: string;
          id?: string;
          mpn: string;
          option_label?: string | null;
          product_id: string;
          sku: string;
          sort_order?: number;
        };
        Update: {
          gtin?: string;
          id?: string;
          mpn?: string;
          option_label?: string | null;
          product_id?: string;
          sku?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "variants_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      webhook_outbox: {
        Row: {
          attempts: number;
          created_at: string;
          delivered_at: string | null;
          event_id: string;
          event_type: string;
          failed_at: string | null;
          id: string;
          last_error: string | null;
          next_attempt_at: string;
          order_id: string;
          payload: NonNullable<Json>;
        };
        Insert: {
          attempts?: number;
          created_at?: string;
          delivered_at?: string | null;
          event_id: string;
          event_type: string;
          failed_at?: string | null;
          id?: string;
          last_error?: string | null;
          next_attempt_at?: string;
          order_id: string;
          payload: NonNullable<Json>;
        };
        Update: {
          attempts?: number;
          created_at?: string;
          delivered_at?: string | null;
          event_id?: string;
          event_type?: string;
          failed_at?: string | null;
          id?: string;
          last_error?: string | null;
          next_attempt_at?: string;
          order_id?: string;
          payload?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "webhook_outbox_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      apply_mutation: {
        Args: {
          p_actor?: string;
          p_mutation: string;
          p_params?: Json;
          p_scenario?: string;
          p_sku: string;
        };
        Returns: {
          actor: string;
          after: Json | null;
          before: Json | null;
          created_at: string;
          id: number;
          mutation: string;
          scenario: string | null;
          target: NonNullable<Json>;
        };
        SetofOptions: {
          from: "*";
          to: "mutation_log";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      apply_scenario: {
        Args: { p_actor?: string; p_name: string; p_steps: Json };
        Returns: {
          actor: string;
          after: Json | null;
          before: Json | null;
          created_at: string;
          id: number;
          mutation: string;
          scenario: string | null;
          target: NonNullable<Json>;
        }[];
        SetofOptions: {
          from: "*";
          to: "mutation_log";
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      capture_baseline: { Args: Record<PropertyKey, never>; Returns: string };
      claim_session: {
        Args: { p_idempotency_key: string; p_session_id: string };
        Returns: boolean;
      };
      claim_webhooks: {
        Args: { p_limit?: number };
        Returns: {
          attempts: number;
          created_at: string;
          delivered_at: string | null;
          event_id: string;
          event_type: string;
          failed_at: string | null;
          id: string;
          last_error: string | null;
          next_attempt_at: string;
          order_id: string;
          payload: NonNullable<Json>;
        }[];
        SetofOptions: {
          from: "*";
          to: "webhook_outbox";
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      finalize_order: {
        Args: {
          p_event: Json;
          p_order: Json;
          p_session_id: string;
          p_snapshot: Json;
        };
        Returns: {
          agent_key_id: string | null;
          buyer: Json | null;
          checkout_session_id: string;
          contract_ref: Json | null;
          contract_verification: Json | null;
          created_at: string;
          currency: string;
          fulfillment_address: Json | null;
          grant_id: string | null;
          id: string;
          line_items: NonNullable<Json>;
          payment: NonNullable<Json>;
          status: string;
          total_minor: number;
          totals: NonNullable<Json>;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "orders";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      idem_abort: {
        Args: { p_key: string; p_scope: string };
        Returns: undefined;
      };
      idem_begin: {
        Args: { p_key: string; p_request_hash: string; p_scope: string };
        Returns: {
          response: Json;
          state: string;
          status_code: number;
        }[];
      };
      idem_finish: {
        Args: {
          p_key: string;
          p_response: Json;
          p_scope: string;
          p_status_code: number;
        };
        Returns: undefined;
      };
      quote: {
        Args: { p_items: Json };
        Returns: {
          merchandise_minor: number;
          shipping_minor: number;
          tax_minor: number;
          total_minor: number;
        }[];
      };
      record_nonce: {
        Args: { p_key_id: string; p_nonce: string };
        Returns: boolean;
      };
      release_session: {
        Args: { p_messages: Json; p_session_id: string };
        Returns: undefined;
      };
      requeue_failed_webhooks: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
      reset_catalog: {
        Args: { p_actor?: string };
        Returns: {
          actor: string;
          after: Json | null;
          before: Json | null;
          created_at: string;
          id: number;
          mutation: string;
          scenario: string | null;
          target: NonNullable<Json>;
        };
        SetofOptions: {
          from: "*";
          to: "mutation_log";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      set_spec_value: {
        Args: { p_name: string; p_spec: Json; p_value: string };
        Returns: Json;
      };
      sku_state: { Args: { p_sku: string }; Returns: Json };
      update_order_status: {
        Args: { p_event: Json; p_order_id: string; p_status: string };
        Returns: {
          agent_key_id: string | null;
          buyer: Json | null;
          checkout_session_id: string;
          contract_ref: Json | null;
          contract_verification: Json | null;
          created_at: string;
          currency: string;
          fulfillment_address: Json | null;
          grant_id: string | null;
          id: string;
          line_items: NonNullable<Json>;
          payment: NonNullable<Json>;
          status: string;
          total_minor: number;
          totals: NonNullable<Json>;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "orders";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      webhook_result: {
        Args: { p_error?: string; p_id: string; p_ok: boolean };
        Returns: {
          attempts: number;
          created_at: string;
          delivered_at: string | null;
          event_id: string;
          event_type: string;
          failed_at: string | null;
          id: string;
          last_error: string | null;
          next_attempt_at: string;
          order_id: string;
          payload: NonNullable<Json>;
        };
        SetofOptions: {
          from: "*";
          to: "webhook_outbox";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  greathub: {
    Enums: {},
  },
} as const;
