// Generated by `pnpm db:types` from supabase/migrations. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      ai_calls: {
        Row: {
          cached_tokens: number;
          cost_usd_micros: number;
          created_at: string;
          error: string | null;
          fell_back: boolean;
          id: string;
          input_tokens: number;
          latency_ms: number | null;
          model: string;
          output_tokens: number;
          plan_id: string | null;
          provider: string;
          task: Database["public"]["Enums"]["ai_task"];
        };
        Insert: {
          cached_tokens?: number;
          cost_usd_micros?: number;
          created_at?: string;
          error?: string | null;
          fell_back?: boolean;
          id?: string;
          input_tokens?: number;
          latency_ms?: number | null;
          model: string;
          output_tokens?: number;
          plan_id?: string | null;
          provider: string;
          task: Database["public"]["Enums"]["ai_task"];
        };
        Update: {
          cached_tokens?: number;
          cost_usd_micros?: number;
          created_at?: string;
          error?: string | null;
          fell_back?: boolean;
          id?: string;
          input_tokens?: number;
          latency_ms?: number | null;
          model?: string;
          output_tokens?: number;
          plan_id?: string | null;
          provider?: string;
          task?: Database["public"]["Enums"]["ai_task"];
        };
        Relationships: [
          {
            foreignKeyName: "ai_calls_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
        ];
      };
      basket_items: {
        Row: {
          basket_id: string;
          id: string;
          offer_id: string;
          qty: number;
          role: string;
        };
        Insert: {
          basket_id: string;
          id?: string;
          offer_id: string;
          qty?: number;
          role: string;
        };
        Update: {
          basket_id?: string;
          id?: string;
          offer_id?: string;
          qty?: number;
          role?: string;
        };
        Relationships: [
          {
            foreignKeyName: "basket_items_basket_id_fkey";
            columns: ["basket_id"];
            isOneToOne: false;
            referencedRelation: "baskets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "basket_items_offer_id_fkey";
            columns: ["offer_id"];
            isOneToOne: false;
            referencedRelation: "offers";
            referencedColumns: ["id"];
          },
        ];
      };
      baskets: {
        Row: {
          created_at: string;
          id: string;
          label: string;
          plan_id: string;
          solver_run_id: string | null;
        };
        Insert: {
          created_at?: string;
          id?: string;
          label: string;
          plan_id: string;
          solver_run_id?: string | null;
        };
        Update: {
          created_at?: string;
          id?: string;
          label?: string;
          plan_id?: string;
          solver_run_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "baskets_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "baskets_solver_run_id_fkey";
            columns: ["solver_run_id"];
            isOneToOne: false;
            referencedRelation: "solver_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      bench_runs: {
        Row: {
          created_at: string;
          gates: NonNullable<Json>;
          git_sha: string;
          id: string;
          passed: number;
          results: NonNullable<Json>;
          total: number;
        };
        Insert: {
          created_at?: string;
          gates?: NonNullable<Json>;
          git_sha: string;
          id?: string;
          passed: number;
          results: NonNullable<Json>;
          total: number;
        };
        Update: {
          created_at?: string;
          gates?: NonNullable<Json>;
          git_sha?: string;
          id?: string;
          passed?: number;
          results?: NonNullable<Json>;
          total?: number;
        };
        Relationships: [];
      };
      checkout_snapshots: {
        Row: {
          acp_session_id: string;
          contract_version_id: string;
          fetched_at: string;
          id: string;
          merchant_id: string;
          state: NonNullable<Json>;
          state_hash: string;
        };
        Insert: {
          acp_session_id: string;
          contract_version_id: string;
          fetched_at?: string;
          id?: string;
          merchant_id: string;
          state: NonNullable<Json>;
          state_hash: string;
        };
        Update: {
          acp_session_id?: string;
          contract_version_id?: string;
          fetched_at?: string;
          id?: string;
          merchant_id?: string;
          state?: NonNullable<Json>;
          state_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: "checkout_snapshots_contract_version_id_fkey";
            columns: ["contract_version_id"];
            isOneToOne: false;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      consent_diffs: {
        Row: {
          changes: NonNullable<Json>;
          classification: Database["public"]["Enums"]["diff_classification"];
          contract_version_id: string;
          created_at: string;
          current_total_minor: number;
          id: string;
          reproof_report_id: string | null;
          snapshot_id: string | null;
        };
        Insert: {
          changes?: NonNullable<Json>;
          classification: Database["public"]["Enums"]["diff_classification"];
          contract_version_id: string;
          created_at?: string;
          current_total_minor: number;
          id?: string;
          reproof_report_id?: string | null;
          snapshot_id?: string | null;
        };
        Update: {
          changes?: NonNullable<Json>;
          classification?: Database["public"]["Enums"]["diff_classification"];
          contract_version_id?: string;
          created_at?: string;
          current_total_minor?: number;
          id?: string;
          reproof_report_id?: string | null;
          snapshot_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "consent_diffs_contract_version_id_fkey";
            columns: ["contract_version_id"];
            isOneToOne: false;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "consent_diffs_reproof_report_id_fkey";
            columns: ["reproof_report_id"];
            isOneToOne: false;
            referencedRelation: "proof_reports";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "consent_diffs_snapshot_id_fkey";
            columns: ["snapshot_id"];
            isOneToOne: false;
            referencedRelation: "checkout_snapshots";
            referencedColumns: ["id"];
          },
        ];
      };
      contract_signatures: {
        Row: {
          authenticator_data: string;
          body_hash: string;
          challenge: string;
          client_data_json: string;
          contract_version_id: string;
          created_at: string;
          credential_id: string | null;
          credential_public_key: string;
          id: string;
          signature: string;
          verified_at: string | null;
        };
        Insert: {
          authenticator_data: string;
          body_hash: string;
          challenge: string;
          client_data_json: string;
          contract_version_id: string;
          created_at?: string;
          credential_id?: string | null;
          credential_public_key: string;
          id?: string;
          signature: string;
          verified_at?: string | null;
        };
        Update: {
          authenticator_data?: string;
          body_hash?: string;
          challenge?: string;
          client_data_json?: string;
          contract_version_id?: string;
          created_at?: string;
          credential_id?: string | null;
          credential_public_key?: string;
          id?: string;
          signature?: string;
          verified_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "contract_signatures_contract_version_id_fkey";
            columns: ["contract_version_id"];
            isOneToOne: false;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contract_signatures_credential_id_fkey";
            columns: ["credential_id"];
            isOneToOne: false;
            referencedRelation: "signing_credentials";
            referencedColumns: ["id"];
          },
        ];
      };
      contract_versions: {
        Row: {
          autonomy: NonNullable<Json>;
          basket_id: string | null;
          body: NonNullable<Json>;
          body_hash: string;
          contract_id: string;
          created_at: string;
          expires_at: string;
          id: string;
          parent_version_id: string | null;
          plan_id: string;
          proof_report_id: string | null;
          signed_at: string | null;
          status: Database["public"]["Enums"]["contract_status"];
          updated_at: string;
          version: number;
        };
        Insert: {
          autonomy: NonNullable<Json>;
          basket_id?: string | null;
          body: NonNullable<Json>;
          body_hash: string;
          contract_id: string;
          created_at?: string;
          expires_at: string;
          id?: string;
          parent_version_id?: string | null;
          plan_id: string;
          proof_report_id?: string | null;
          signed_at?: string | null;
          status?: Database["public"]["Enums"]["contract_status"];
          updated_at?: string;
          version: number;
        };
        Update: {
          autonomy?: NonNullable<Json>;
          basket_id?: string | null;
          body?: NonNullable<Json>;
          body_hash?: string;
          contract_id?: string;
          created_at?: string;
          expires_at?: string;
          id?: string;
          parent_version_id?: string | null;
          plan_id?: string;
          proof_report_id?: string | null;
          signed_at?: string | null;
          status?: Database["public"]["Enums"]["contract_status"];
          updated_at?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "contract_versions_basket_id_fkey";
            columns: ["basket_id"];
            isOneToOne: false;
            referencedRelation: "baskets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contract_versions_contract_id_plan_id_fkey";
            columns: ["contract_id", "plan_id"];
            isOneToOne: false;
            referencedRelation: "contracts";
            referencedColumns: ["id", "plan_id"];
          },
          {
            foreignKeyName: "contract_versions_parent_version_id_fkey";
            columns: ["parent_version_id"];
            isOneToOne: false;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contract_versions_proof_report_id_fkey";
            columns: ["proof_report_id"];
            isOneToOne: false;
            referencedRelation: "proof_reports";
            referencedColumns: ["id"];
          },
        ];
      };
      contracts: {
        Row: {
          created_at: string;
          id: string;
          plan_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          plan_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          plan_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contracts_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
        ];
      };
      evidence_packs: {
        Row: {
          created_at: string;
          id: string;
          order_id: string;
          sha256: string;
          storage_path: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          order_id: string;
          sha256: string;
          storage_path: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          order_id?: string;
          sha256?: string;
          storage_path?: string;
        };
        Relationships: [
          {
            foreignKeyName: "evidence_packs_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      facts: {
        Row: {
          conflict: boolean;
          created_at: string;
          extractor: string;
          field: string;
          fresh_until: string | null;
          id: string;
          qualifier: string | null;
          quote: string | null;
          raw: string | null;
          retrieved_at: string;
          source_id: string;
          span: unknown;
          state: Database["public"]["Enums"]["evidence_state"];
          state_reason: string | null;
          subject_id: string;
          subject_kind: Database["public"]["Enums"]["fact_subject_kind"];
          superseded_by: string | null;
          unit: string | null;
          value: Json | null;
        };
        Insert: {
          conflict?: boolean;
          created_at?: string;
          extractor: string;
          field: string;
          fresh_until?: string | null;
          id?: string;
          qualifier?: string | null;
          quote?: string | null;
          raw?: string | null;
          retrieved_at?: string;
          source_id: string;
          span?: unknown;
          state: Database["public"]["Enums"]["evidence_state"];
          state_reason?: string | null;
          subject_id: string;
          subject_kind: Database["public"]["Enums"]["fact_subject_kind"];
          superseded_by?: string | null;
          unit?: string | null;
          value?: Json | null;
        };
        Update: {
          conflict?: boolean;
          created_at?: string;
          extractor?: string;
          field?: string;
          fresh_until?: string | null;
          id?: string;
          qualifier?: string | null;
          quote?: string | null;
          raw?: string | null;
          retrieved_at?: string;
          source_id?: string;
          span?: unknown;
          state?: Database["public"]["Enums"]["evidence_state"];
          state_reason?: string | null;
          subject_id?: string;
          subject_kind?: Database["public"]["Enums"]["fact_subject_kind"];
          superseded_by?: string | null;
          unit?: string | null;
          value?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: "facts_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "facts_superseded_by_fkey";
            columns: ["superseded_by"];
            isOneToOne: false;
            referencedRelation: "facts";
            referencedColumns: ["id"];
          },
        ];
      };
      foundation_events: {
        Row: {
          created_at: string;
          id: string;
          plan_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          plan_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          plan_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "foundation_events_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "foundation_plans";
            referencedColumns: ["id"];
          },
        ];
      };
      foundation_plans: {
        Row: {
          created_at: string;
          id: string;
          owner_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          owner_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          owner_id?: string;
        };
        Relationships: [];
      };
      kit_items: {
        Row: {
          id: string;
          kit_slug: string;
          product_id: string;
          qty: number;
          role: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          kit_slug: string;
          product_id: string;
          qty?: number;
          role: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          kit_slug?: string;
          product_id?: string;
          qty?: number;
          role?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "kit_items_kit_slug_fkey";
            columns: ["kit_slug"];
            isOneToOne: false;
            referencedRelation: "kits";
            referencedColumns: ["slug"];
          },
          {
            foreignKeyName: "kit_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      kit_requirements: {
        Row: {
          id: string;
          importance: Database["public"]["Enums"]["requirement_importance"];
          kit_slug: string;
          requirement_key: string;
          sort_order: number;
          spec: NonNullable<Json>;
        };
        Insert: {
          id?: string;
          importance: Database["public"]["Enums"]["requirement_importance"];
          kit_slug: string;
          requirement_key: string;
          sort_order?: number;
          spec: NonNullable<Json>;
        };
        Update: {
          id?: string;
          importance?: Database["public"]["Enums"]["requirement_importance"];
          kit_slug?: string;
          requirement_key?: string;
          sort_order?: number;
          spec?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "kit_requirements_kit_slug_fkey";
            columns: ["kit_slug"];
            isOneToOne: false;
            referencedRelation: "kits";
            referencedColumns: ["slug"];
          },
        ];
      };
      kits: {
        Row: {
          created_at: string;
          description: string;
          hero_figure: string | null;
          pack: string;
          slug: string;
          sort_order: number;
          title: string;
        };
        Insert: {
          created_at?: string;
          description: string;
          hero_figure?: string | null;
          pack: string;
          slug: string;
          sort_order?: number;
          title: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          hero_figure?: string | null;
          pack?: string;
          slug?: string;
          sort_order?: number;
          title?: string;
        };
        Relationships: [];
      };
      ledger_events: {
        Row: {
          actor: string;
          created_at: string;
          hash: string;
          id: number;
          payload: NonNullable<Json>;
          plan_id: string;
          prev_hash: string;
          seq: number;
          type: string;
        };
        Insert: {
          actor: string;
          created_at?: string;
          hash: string;
          id?: never;
          payload?: NonNullable<Json>;
          plan_id: string;
          prev_hash: string;
          seq: number;
          type: string;
        };
        Update: {
          actor?: string;
          created_at?: string;
          hash?: string;
          id?: never;
          payload?: NonNullable<Json>;
          plan_id?: string;
          prev_hash?: string;
          seq?: number;
          type?: string;
        };
        Relationships: [];
      };
      mandates: {
        Row: {
          attempts: number;
          contract_version_id: string;
          created_at: string;
          fired_at: string | null;
          id: string;
          last_checked_at: string | null;
          next_check_at: string;
          not_after: string;
          outcome: Json | null;
          status: Database["public"]["Enums"]["mandate_status"];
          trigger: NonNullable<Json>;
          updated_at: string;
        };
        Insert: {
          attempts?: number;
          contract_version_id: string;
          created_at?: string;
          fired_at?: string | null;
          id?: string;
          last_checked_at?: string | null;
          next_check_at?: string;
          not_after: string;
          outcome?: Json | null;
          status?: Database["public"]["Enums"]["mandate_status"];
          trigger: NonNullable<Json>;
          updated_at?: string;
        };
        Update: {
          attempts?: number;
          contract_version_id?: string;
          created_at?: string;
          fired_at?: string | null;
          id?: string;
          last_checked_at?: string | null;
          next_check_at?: string;
          not_after?: string;
          outcome?: Json | null;
          status?: Database["public"]["Enums"]["mandate_status"];
          trigger?: NonNullable<Json>;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mandates_contract_version_id_fkey";
            columns: ["contract_version_id"];
            isOneToOne: true;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      offers: {
        Row: {
          availability: Database["public"]["Enums"]["availability"];
          created_at: string;
          currency: string;
          delivery_earliest: string | null;
          delivery_latest: string | null;
          external_id: string;
          final_sale: boolean | null;
          fresh_until: string;
          id: string;
          merchant_id: string;
          price_minor: number | null;
          product_id: string;
          reference_only: boolean;
          retrieved_at: string;
          return_policy: Json | null;
          seller_id: string | null;
          shipping_minor: number | null;
          source: string;
          updated_at: string;
          url: string | null;
        };
        Insert: {
          availability?: Database["public"]["Enums"]["availability"];
          created_at?: string;
          currency?: string;
          delivery_earliest?: string | null;
          delivery_latest?: string | null;
          external_id: string;
          final_sale?: boolean | null;
          fresh_until: string;
          id?: string;
          merchant_id: string;
          price_minor?: number | null;
          product_id: string;
          reference_only?: boolean;
          retrieved_at?: string;
          return_policy?: Json | null;
          seller_id?: string | null;
          shipping_minor?: number | null;
          source: string;
          updated_at?: string;
          url?: string | null;
        };
        Update: {
          availability?: Database["public"]["Enums"]["availability"];
          created_at?: string;
          currency?: string;
          delivery_earliest?: string | null;
          delivery_latest?: string | null;
          external_id?: string;
          final_sale?: boolean | null;
          fresh_until?: string;
          id?: string;
          merchant_id?: string;
          price_minor?: number | null;
          product_id?: string;
          reference_only?: boolean;
          retrieved_at?: string;
          return_policy?: Json | null;
          seller_id?: string | null;
          shipping_minor?: number | null;
          source?: string;
          updated_at?: string;
          url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "offers_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          created_at: string;
          currency: string;
          events: NonNullable<Json>;
          execution_id: string;
          id: string;
          merchant_id: string;
          merchant_order_id: string;
          status: Database["public"]["Enums"]["order_status"];
          total_minor: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency?: string;
          events?: NonNullable<Json>;
          execution_id: string;
          id?: string;
          merchant_id: string;
          merchant_order_id: string;
          status?: Database["public"]["Enums"]["order_status"];
          total_minor: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          events?: NonNullable<Json>;
          execution_id?: string;
          id?: string;
          merchant_id?: string;
          merchant_order_id?: string;
          status?: Database["public"]["Enums"]["order_status"];
          total_minor?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_execution_id_fkey";
            columns: ["execution_id"];
            isOneToOne: true;
            referencedRelation: "payment_executions";
            referencedColumns: ["id"];
          },
        ];
      };
      payment_executions: {
        Row: {
          amount_minor: number;
          completed_at: string | null;
          contract_version_id: string;
          created_at: string;
          currency: string;
          diff_id: string;
          error: Json | null;
          id: string;
          idempotency_key: string;
          instrument_id: string | null;
          rail: Database["public"]["Enums"]["payment_rail"] | null;
          rail_ref: string | null;
          status: Database["public"]["Enums"]["execution_status"];
          token_consumed_at: string | null;
        };
        Insert: {
          amount_minor: number;
          completed_at?: string | null;
          contract_version_id: string;
          created_at?: string;
          currency?: string;
          diff_id: string;
          error?: Json | null;
          id?: string;
          idempotency_key: string;
          instrument_id?: string | null;
          rail?: Database["public"]["Enums"]["payment_rail"] | null;
          rail_ref?: string | null;
          status?: Database["public"]["Enums"]["execution_status"];
          token_consumed_at?: string | null;
        };
        Update: {
          amount_minor?: number;
          completed_at?: string | null;
          contract_version_id?: string;
          created_at?: string;
          currency?: string;
          diff_id?: string;
          error?: Json | null;
          id?: string;
          idempotency_key?: string;
          instrument_id?: string | null;
          rail?: Database["public"]["Enums"]["payment_rail"] | null;
          rail_ref?: string | null;
          status?: Database["public"]["Enums"]["execution_status"];
          token_consumed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "payment_executions_contract_version_id_fkey";
            columns: ["contract_version_id"];
            isOneToOne: false;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payment_executions_diff_id_fkey";
            columns: ["diff_id"];
            isOneToOne: false;
            referencedRelation: "consent_diffs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payment_executions_instrument_id_fkey";
            columns: ["instrument_id"];
            isOneToOne: false;
            referencedRelation: "payment_instruments";
            referencedColumns: ["id"];
          },
        ];
      };
      payment_instruments: {
        Row: {
          brand: string | null;
          created_at: string;
          exp_month: number | null;
          exp_year: number | null;
          id: string;
          is_default: boolean;
          last4: string | null;
          rail: Database["public"]["Enums"]["payment_rail"];
          rail_ref: string;
          user_id: string;
        };
        Insert: {
          brand?: string | null;
          created_at?: string;
          exp_month?: number | null;
          exp_year?: number | null;
          id?: string;
          is_default?: boolean;
          last4?: string | null;
          rail: Database["public"]["Enums"]["payment_rail"];
          rail_ref: string;
          user_id: string;
        };
        Update: {
          brand?: string | null;
          created_at?: string;
          exp_month?: number | null;
          exp_year?: number | null;
          id?: string;
          is_default?: boolean;
          last4?: string | null;
          rail?: Database["public"]["Enums"]["payment_rail"];
          rail_ref?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          brief: string | null;
          created_at: string;
          id: string;
          packs: string[];
          status: Database["public"]["Enums"]["plan_status"];
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          brief?: string | null;
          created_at?: string;
          id?: string;
          packs?: string[];
          status?: Database["public"]["Enums"]["plan_status"];
          title: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          brief?: string | null;
          created_at?: string;
          id?: string;
          packs?: string[];
          status?: Database["public"]["Enums"]["plan_status"];
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      product_external_refs: {
        Row: {
          created_at: string;
          external_id: string;
          gtin: string | null;
          id: string;
          product_id: string;
          source: string;
          upid: string | null;
          url: string | null;
        };
        Insert: {
          created_at?: string;
          external_id: string;
          gtin?: string | null;
          id?: string;
          product_id: string;
          source: string;
          upid?: string | null;
          url?: string | null;
        };
        Update: {
          created_at?: string;
          external_id?: string;
          gtin?: string | null;
          id?: string;
          product_id?: string;
          source?: string;
          upid?: string | null;
          url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "product_external_refs_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      products: {
        Row: {
          attributes: NonNullable<Json>;
          brand: string | null;
          category: string | null;
          created_at: string;
          external_id: string | null;
          gtin: string | null;
          id: string;
          image_url: string | null;
          merchant_id: string | null;
          mpn: string | null;
          roles: string[];
          search_tsv: unknown;
          source: string;
          title: string;
          updated_at: string;
          upid: string | null;
        };
        Insert: {
          attributes?: NonNullable<Json>;
          brand?: string | null;
          category?: string | null;
          created_at?: string;
          external_id?: string | null;
          gtin?: string | null;
          id?: string;
          image_url?: string | null;
          merchant_id?: string | null;
          mpn?: string | null;
          roles?: string[];
          search_tsv?: never;
          source: string;
          title: string;
          updated_at?: string;
          upid?: string | null;
        };
        Update: {
          attributes?: NonNullable<Json>;
          brand?: string | null;
          category?: string | null;
          created_at?: string;
          external_id?: string | null;
          gtin?: string | null;
          id?: string;
          image_url?: string | null;
          merchant_id?: string | null;
          mpn?: string | null;
          roles?: string[];
          search_tsv?: never;
          source?: string;
          title?: string;
          updated_at?: string;
          upid?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          created_at: string;
          default_autonomy: Database["public"]["Enums"]["autonomy_preset"];
          display_name: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          default_autonomy?: Database["public"]["Enums"]["autonomy_preset"];
          display_name?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          default_autonomy?: Database["public"]["Enums"]["autonomy_preset"];
          display_name?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      proof_reports: {
        Row: {
          basket_id: string;
          created_at: string;
          engine_version: string;
          evaluated_at: string;
          hash: string;
          id: string;
          kind: Database["public"]["Enums"]["proof_report_kind"];
          packs: NonNullable<Json>;
          report: NonNullable<Json>;
          set_id: string;
          summary: NonNullable<Json>;
        };
        Insert: {
          basket_id: string;
          created_at?: string;
          engine_version: string;
          evaluated_at: string;
          hash: string;
          id?: string;
          kind?: Database["public"]["Enums"]["proof_report_kind"];
          packs: NonNullable<Json>;
          report: NonNullable<Json>;
          set_id: string;
          summary: NonNullable<Json>;
        };
        Update: {
          basket_id?: string;
          created_at?: string;
          engine_version?: string;
          evaluated_at?: string;
          hash?: string;
          id?: string;
          kind?: Database["public"]["Enums"]["proof_report_kind"];
          packs?: NonNullable<Json>;
          report?: NonNullable<Json>;
          set_id?: string;
          summary?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "proof_reports_basket_id_fkey";
            columns: ["basket_id"];
            isOneToOne: false;
            referencedRelation: "baskets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "proof_reports_set_id_fkey";
            columns: ["set_id"];
            isOneToOne: false;
            referencedRelation: "requirement_sets";
            referencedColumns: ["id"];
          },
        ];
      };
      proof_results: {
        Row: {
          created_at: string;
          fact_ids: string[];
          id: string;
          observed: Json | null;
          reason: string | null;
          report_id: string;
          requirement_id: string;
          scope: NonNullable<Json>;
          state: Database["public"]["Enums"]["evidence_state"];
          target: Json | null;
          verdict: Database["public"]["Enums"]["verdict"];
        };
        Insert: {
          created_at?: string;
          fact_ids?: string[];
          id?: string;
          observed?: Json | null;
          reason?: string | null;
          report_id: string;
          requirement_id: string;
          scope: NonNullable<Json>;
          state: Database["public"]["Enums"]["evidence_state"];
          target?: Json | null;
          verdict: Database["public"]["Enums"]["verdict"];
        };
        Update: {
          created_at?: string;
          fact_ids?: string[];
          id?: string;
          observed?: Json | null;
          reason?: string | null;
          report_id?: string;
          requirement_id?: string;
          scope?: NonNullable<Json>;
          state?: Database["public"]["Enums"]["evidence_state"];
          target?: Json | null;
          verdict?: Database["public"]["Enums"]["verdict"];
        };
        Relationships: [
          {
            foreignKeyName: "proof_results_report_id_fkey";
            columns: ["report_id"];
            isOneToOne: false;
            referencedRelation: "proof_reports";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "proof_results_requirement_id_fkey";
            columns: ["requirement_id"];
            isOneToOne: false;
            referencedRelation: "requirements";
            referencedColumns: ["id"];
          },
        ];
      };
      requirement_sets: {
        Row: {
          created_at: string;
          created_by: string;
          hash: string;
          id: string;
          parent_id: string | null;
          plan_id: string;
          version: number;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          hash: string;
          id?: string;
          parent_id?: string | null;
          plan_id: string;
          version: number;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          hash?: string;
          id?: string;
          parent_id?: string | null;
          plan_id?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "requirement_sets_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "requirement_sets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "requirement_sets_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
        ];
      };
      requirements: {
        Row: {
          confirmed: boolean;
          created_at: string;
          effective_importance:
            | Database["public"]["Enums"]["requirement_importance"]
            | null;
          id: string;
          importance: Database["public"]["Enums"]["requirement_importance"];
          provenance_kind: Database["public"]["Enums"]["provenance_kind"];
          requirement_key: string;
          set_id: string;
          spec: NonNullable<Json>;
        };
        Insert: {
          confirmed?: boolean;
          created_at?: string;
          effective_importance?: never;
          id?: string;
          importance: Database["public"]["Enums"]["requirement_importance"];
          provenance_kind: Database["public"]["Enums"]["provenance_kind"];
          requirement_key: string;
          set_id: string;
          spec: NonNullable<Json>;
        };
        Update: {
          confirmed?: boolean;
          created_at?: string;
          effective_importance?: never;
          id?: string;
          importance?: Database["public"]["Enums"]["requirement_importance"];
          provenance_kind?: Database["public"]["Enums"]["provenance_kind"];
          requirement_key?: string;
          set_id?: string;
          spec?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "requirements_set_id_fkey";
            columns: ["set_id"];
            isOneToOne: false;
            referencedRelation: "requirement_sets";
            referencedColumns: ["id"];
          },
        ];
      };
      search_queries: {
        Row: {
          created_at: string;
          id: string;
          query: NonNullable<Json>;
          query_hash: string;
          result_product_ids: string[];
          source_status: NonNullable<Json>;
        };
        Insert: {
          created_at?: string;
          id?: string;
          query: NonNullable<Json>;
          query_hash: string;
          result_product_ids?: string[];
          source_status?: NonNullable<Json>;
        };
        Update: {
          created_at?: string;
          id?: string;
          query?: NonNullable<Json>;
          query_hash?: string;
          result_product_ids?: string[];
          source_status?: NonNullable<Json>;
        };
        Relationships: [];
      };
      signing_challenges: {
        Row: {
          body_hash: string;
          challenge: string;
          contract_version_id: string;
          created_at: string;
          expires_at: string;
          nonce: string;
          user_id: string;
        };
        Insert: {
          body_hash: string;
          challenge: string;
          contract_version_id: string;
          created_at?: string;
          expires_at?: string;
          nonce: string;
          user_id: string;
        };
        Update: {
          body_hash?: string;
          challenge?: string;
          contract_version_id?: string;
          created_at?: string;
          expires_at?: string;
          nonce?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "signing_challenges_contract_version_id_fkey";
            columns: ["contract_version_id"];
            isOneToOne: false;
            referencedRelation: "contract_versions";
            referencedColumns: ["id"];
          },
        ];
      };
      signing_credentials: {
        Row: {
          counter: number;
          created_at: string;
          credential_id: string;
          device_label: string | null;
          id: string;
          last_used_at: string | null;
          public_key: string;
          transports: string[];
          user_id: string;
        };
        Insert: {
          counter?: number;
          created_at?: string;
          credential_id: string;
          device_label?: string | null;
          id?: string;
          last_used_at?: string | null;
          public_key: string;
          transports?: string[];
          user_id: string;
        };
        Update: {
          counter?: number;
          created_at?: string;
          credential_id?: string;
          device_label?: string | null;
          id?: string;
          last_used_at?: string | null;
          public_key?: string;
          transports?: string[];
          user_id?: string;
        };
        Relationships: [];
      };
      solver_runs: {
        Row: {
          conflict_set: Json | null;
          created_at: string;
          id: string;
          input_hash: string;
          ms: number | null;
          objective: number | null;
          plan_id: string;
          relaxations: Json | null;
          set_id: string;
          status: Database["public"]["Enums"]["solver_status"];
        };
        Insert: {
          conflict_set?: Json | null;
          created_at?: string;
          id?: string;
          input_hash: string;
          ms?: number | null;
          objective?: number | null;
          plan_id: string;
          relaxations?: Json | null;
          set_id: string;
          status: Database["public"]["Enums"]["solver_status"];
        };
        Update: {
          conflict_set?: Json | null;
          created_at?: string;
          id?: string;
          input_hash?: string;
          ms?: number | null;
          objective?: number | null;
          plan_id?: string;
          relaxations?: Json | null;
          set_id?: string;
          status?: Database["public"]["Enums"]["solver_status"];
        };
        Relationships: [
          {
            foreignKeyName: "solver_runs_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "solver_runs_set_id_fkey";
            columns: ["set_id"];
            isOneToOne: false;
            referencedRelation: "requirement_sets";
            referencedColumns: ["id"];
          },
        ];
      };
      sources: {
        Row: {
          content_hash: string;
          content_type: string | null;
          created_at: string;
          fetched_at: string;
          http_status: number | null;
          id: string;
          source_type: string;
          storage_path: string | null;
          url: string;
        };
        Insert: {
          content_hash: string;
          content_type?: string | null;
          created_at?: string;
          fetched_at?: string;
          http_status?: number | null;
          id?: string;
          source_type: string;
          storage_path?: string | null;
          url: string;
        };
        Update: {
          content_hash?: string;
          content_type?: string | null;
          created_at?: string;
          fetched_at?: string;
          http_status?: number | null;
          id?: string;
          source_type?: string;
          storage_path?: string | null;
          url?: string;
        };
        Relationships: [];
      };
      webhook_events: {
        Row: {
          error: string | null;
          event_id: string;
          event_type: string;
          id: string;
          payload: NonNullable<Json>;
          processed_at: string | null;
          provider: string;
          received_at: string;
        };
        Insert: {
          error?: string | null;
          event_id: string;
          event_type: string;
          id?: string;
          payload: NonNullable<Json>;
          processed_at?: string | null;
          provider: string;
          received_at?: string;
        };
        Update: {
          error?: string | null;
          event_id?: string;
          event_type?: string;
          id?: string;
          payload?: NonNullable<Json>;
          processed_at?: string | null;
          provider?: string;
          received_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      catalog_search_products: {
        Args: {
          p_ids?: string[];
          p_limit?: number;
          p_query: string;
          p_source: string;
        };
        Returns: {
          product_id: string;
          rank: number;
        }[];
      };
      foundation_health: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_valid_gtin: { Args: { p_gtin: string }; Returns: boolean };
      search_products: {
        Args: { p_limit?: number; p_query: string };
        Returns: {
          brand: string;
          category: string;
          gtin: string;
          image_url: string;
          product_id: string;
          rank: number;
          roles: string[];
          title: string;
        }[];
      };
      srv_arm_mandate: {
        Args: { p_actor: string; p_version: string };
        Returns: {
          attempts: number;
          contract_version_id: string;
          created_at: string;
          fired_at: string | null;
          id: string;
          last_checked_at: string | null;
          next_check_at: string;
          not_after: string;
          outcome: Json | null;
          status: Database["public"]["Enums"]["mandate_status"];
          trigger: NonNullable<Json>;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "mandates";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_begin_execution: {
        Args: {
          p_diff: string;
          p_idem: string;
          p_instrument?: string;
          p_rail?: Database["public"]["Enums"]["payment_rail"];
          p_version: string;
        };
        Returns: string;
      };
      srv_begin_signing: {
        Args: {
          p_challenge: string;
          p_hash: string;
          p_nonce: string;
          p_user: string;
          p_version: string;
        };
        Returns: string;
      };
      srv_begin_signing_registration: {
        Args: { p_challenge: string; p_user: string };
        Returns: string;
      };
      srv_bind_approved_checkout: {
        Args: {
          p_hash: string;
          p_merchant: string;
          p_session: string;
          p_state: Json;
          p_version: string;
        };
        Returns: string;
      };
      srv_cancel_mandate: {
        Args: { p_actor: string; p_mandate: string };
        Returns: {
          attempts: number;
          contract_version_id: string;
          created_at: string;
          fired_at: string | null;
          id: string;
          last_checked_at: string | null;
          next_check_at: string;
          not_after: string;
          outcome: Json | null;
          status: Database["public"]["Enums"]["mandate_status"];
          trigger: NonNullable<Json>;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "mandates";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_catalog_identity: { Args: { p_product: Json }; Returns: string };
      srv_complete_execution: {
        Args: {
          p_error?: Json;
          p_execution: string;
          p_merchant_id?: string;
          p_merchant_order_id?: string;
          p_rail_ref?: string;
          p_status: Database["public"]["Enums"]["execution_status"];
        };
        Returns: {
          amount_minor: number;
          completed_at: string | null;
          contract_version_id: string;
          created_at: string;
          currency: string;
          diff_id: string;
          error: Json | null;
          id: string;
          idempotency_key: string;
          instrument_id: string | null;
          rail: Database["public"]["Enums"]["payment_rail"] | null;
          rail_ref: string | null;
          status: Database["public"]["Enums"]["execution_status"];
          token_consumed_at: string | null;
        };
        SetofOptions: {
          from: "*";
          to: "payment_executions";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_consume_execution_token: {
        Args: { p_execution: string };
        Returns: {
          amount_minor: number;
          completed_at: string | null;
          contract_version_id: string;
          created_at: string;
          currency: string;
          diff_id: string;
          error: Json | null;
          id: string;
          idempotency_key: string;
          instrument_id: string | null;
          rail: Database["public"]["Enums"]["payment_rail"] | null;
          rail_ref: string | null;
          status: Database["public"]["Enums"]["execution_status"];
          token_consumed_at: string | null;
        };
        SetofOptions: {
          from: "*";
          to: "payment_executions";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_consume_signing_challenge: {
        Args: { p_nonce: string; p_user: string };
        Returns: {
          body_hash: string;
          challenge: string;
          contract_version_id: string;
          expired: boolean;
        }[];
      };
      srv_consume_signing_registration: {
        Args: { p_challenge: string; p_user: string };
        Returns: boolean;
      };
      srv_fork_kit: {
        Args: {
          p_hash: string;
          p_slug: string;
          p_specs: Json;
          p_user_id: string;
        };
        Returns: Json;
      };
      srv_ledger_append: {
        Args: {
          p_actor: string;
          p_payload?: Json;
          p_plan_id: string;
          p_type: string;
        };
        Returns: {
          actor: string;
          created_at: string;
          hash: string;
          id: number;
          payload: NonNullable<Json>;
          plan_id: string;
          prev_hash: string;
          seq: number;
          type: string;
        };
        SetofOptions: {
          from: "*";
          to: "ledger_events";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_mandates_tick: { Args: Record<PropertyKey, never>; Returns: number };
      srv_queue_archive: {
        Args: { p_msg_id: number; p_queue: string };
        Returns: boolean;
      };
      srv_queue_read: {
        Args: { p_qty?: number; p_queue: string; p_vt?: number };
        Returns: unknown[];
        SetofOptions: {
          from: "*";
          to: "message_record";
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      srv_queue_send: {
        Args: { p_delay?: number; p_message: Json; p_queue: string };
        Returns: number;
      };
      srv_receive_greathub_event: { Args: { p_event: Json }; Returns: string };
      srv_record_checkout_proof: {
        Args: {
          p_diff: Json;
          p_hash: string;
          p_merchant: string;
          p_report: Json;
          p_session: string;
          p_state: Json;
          p_version: string;
        };
        Returns: string;
      };
      srv_record_contract_signature: {
        Args: {
          p_authenticator_data: string;
          p_challenge: string;
          p_client_data_json: string;
          p_counter: number;
          p_credential: string;
          p_hash: string;
          p_signature: string;
          p_user: string;
          p_version: string;
        };
        Returns: string;
      };
      srv_record_delivery: {
        Args: {
          p_order: string;
          p_payload: Json;
          p_type: string;
          p_user: string;
        };
        Returns: {
          actor: string;
          created_at: string;
          hash: string;
          id: number;
          payload: NonNullable<Json>;
          plan_id: string;
          prev_hash: string;
          seq: number;
          type: string;
        };
        SetofOptions: {
          from: "*";
          to: "ledger_events";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_record_evidence_pack: {
        Args: { p_order: string; p_path: string; p_sha256: string };
        Returns: {
          created_at: string;
          id: string;
          order_id: string;
          sha256: string;
          storage_path: string;
        };
        SetofOptions: {
          from: "*";
          to: "evidence_packs";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_record_handoff: {
        Args: { p_diff: string; p_url: string; p_version: string };
        Returns: undefined;
      };
      srv_record_mandate: {
        Args: {
          p_kind: string;
          p_mandate: string;
          p_observation?: Json;
          p_outcome?: Json;
          p_status?: Database["public"]["Enums"]["mandate_status"];
        };
        Returns: {
          attempts: number;
          contract_version_id: string;
          created_at: string;
          fired_at: string | null;
          id: string;
          last_checked_at: string | null;
          next_check_at: string;
          not_after: string;
          outcome: Json | null;
          status: Database["public"]["Enums"]["mandate_status"];
          trigger: NonNullable<Json>;
          updated_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "mandates";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_transition_contract: {
        Args: {
          p_actor?: string;
          p_event?: string;
          p_payload?: Json;
          p_to: Database["public"]["Enums"]["contract_status"];
          p_version: string;
        };
        Returns: {
          autonomy: NonNullable<Json>;
          basket_id: string | null;
          body: NonNullable<Json>;
          body_hash: string;
          contract_id: string;
          created_at: string;
          expires_at: string;
          id: string;
          parent_version_id: string | null;
          plan_id: string;
          proof_report_id: string | null;
          signed_at: string | null;
          status: Database["public"]["Enums"]["contract_status"];
          updated_at: string;
          version: number;
        };
        SetofOptions: {
          from: "*";
          to: "contract_versions";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      srv_verify_ledger: { Args: { p_plan_id: string }; Returns: number };
      srv_write_facts: { Args: { p_groups: Json }; Returns: string[] };
    };
    Enums: {
      ai_task: "A1" | "A2" | "A3" | "A4" | "A5";
      autonomy_preset: "strict" | "balanced" | "flexible";
      availability:
        | "in_stock"
        | "limited"
        | "backorder"
        | "preorder"
        | "out_of_stock"
        | "discontinued"
        | "unknown";
      contract_status:
        | "draft"
        | "awaiting_signature"
        | "signed"
        | "armed"
        | "executing"
        | "executed"
        | "failed"
        | "invalidated"
        | "superseded"
        | "expired";
      diff_classification: "identical" | "auto" | "reapprove" | "block";
      evidence_state:
        | "unknown"
        | "estimated"
        | "supported"
        | "source_stated"
        | "verified";
      execution_status: "started" | "authorized" | "declined" | "error";
      fact_subject_kind: "product" | "offer";
      mandate_status:
        | "armed"
        | "fired_executed"
        | "fired_blocked"
        | "expired"
        | "cancelled";
      order_status:
        | "created"
        | "manual_review"
        | "confirmed"
        | "canceled"
        | "shipped"
        | "fulfilled";
      payment_rail: "visa_acceptance" | "vic" | "authorize_net" | "simulated";
      plan_status:
        | "draft"
        | "solving"
        | "ready"
        | "contracted"
        | "purchased"
        | "archived";
      proof_report_kind: "plan" | "reproof";
      provenance_kind:
        | "user_stated"
        | "ai_inferred"
        | "user_selected"
        | "pack_default";
      requirement_importance: "hard" | "preference";
      solver_status: "optimal" | "infeasible" | "error";
      verdict: "pass" | "fail" | "unknown";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      ai_task: ["A1", "A2", "A3", "A4", "A5"],
      autonomy_preset: ["strict", "balanced", "flexible"],
      availability: [
        "in_stock",
        "limited",
        "backorder",
        "preorder",
        "out_of_stock",
        "discontinued",
        "unknown",
      ],
      contract_status: [
        "draft",
        "awaiting_signature",
        "signed",
        "armed",
        "executing",
        "executed",
        "failed",
        "invalidated",
        "superseded",
        "expired",
      ],
      diff_classification: ["identical", "auto", "reapprove", "block"],
      evidence_state: [
        "unknown",
        "estimated",
        "supported",
        "source_stated",
        "verified",
      ],
      execution_status: ["started", "authorized", "declined", "error"],
      fact_subject_kind: ["product", "offer"],
      mandate_status: [
        "armed",
        "fired_executed",
        "fired_blocked",
        "expired",
        "cancelled",
      ],
      order_status: [
        "created",
        "manual_review",
        "confirmed",
        "canceled",
        "shipped",
        "fulfilled",
      ],
      payment_rail: ["visa_acceptance", "vic", "authorize_net", "simulated"],
      plan_status: [
        "draft",
        "solving",
        "ready",
        "contracted",
        "purchased",
        "archived",
      ],
      proof_report_kind: ["plan", "reproof"],
      provenance_kind: [
        "user_stated",
        "ai_inferred",
        "user_selected",
        "pack_default",
      ],
      requirement_importance: ["hard", "preference"],
      solver_status: ["optimal", "infeasible", "error"],
      verdict: ["pass", "fail", "unknown"],
    },
  },
} as const;
