#!/usr/bin/env node
// Generates Supabase types from the local database (T2.14).
//   node scripts/db-types.mjs          write the files
//   node scripts/db-types.mjs --check  exit 1 if a committed file is stale (CI)
//
// Cartel and GreatHub get separate files: Cartel code never imports GreatHub types.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const bin = (name) => join(root, "node_modules", ".bin", name);
const targets = [
  { schema: "public", file: "packages/contracts/src/db.ts" },
  { schema: "greathub", file: "apps/greathub/lib/supabase/db.ts" },
];
const header =
  "// Generated by `pnpm db:types` from supabase/migrations. Do not edit by hand.\n";

function generate(schema) {
  const raw = execFileSync(
    bin("supabase"),
    ["gen", "types", "typescript", "--local", "--schema", schema],
    {
      cwd: root,
      encoding: "utf8",
      maxBuffer: 16 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    },
  );
  // Biome's stdin formatter can hang on the CLI's compact generated types.
  // Format a temporary file instead; never overwrite committed types in --check mode.
  const temporary = mkdtempSync(join(tmpdir(), "cartel-db-types-"));
  const path = join(temporary, "db.ts");
  try {
    writeFileSync(path, header + raw);
    execFileSync(
      bin("biome"),
      ["format", "--write", `--config-path=${root}`, path],
      {
        cwd: root,
        encoding: "utf8",
        timeout: 30_000,
      },
    );
    return readFileSync(path, "utf8");
  } finally {
    rmSync(temporary, { recursive: true, force: true });
  }
}

const check = process.argv.includes("--check");
let stale = false;
for (const { schema, file } of targets) {
  const fresh = generate(schema);
  const path = join(root, file);
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {}
    if (current !== fresh) {
      console.error(`${file} is stale; run \`pnpm db:types\` and commit it.`);
      stale = true;
    }
  } else {
    writeFileSync(path, fresh);
    console.log(`wrote ${file} (${schema})`);
  }
}
process.exit(stale ? 1 : 0);
