#!/usr/bin/env node
// Generates Supabase types from the local database (T2.14).
//   node scripts/db-types.mjs          write the files
//   node scripts/db-types.mjs --check  exit 1 if a committed file is stale (CI)
//
// ProofCart and DemoMart get separate files: ProofCart code never imports DemoMart types.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const bin = (name) => join(root, "node_modules", ".bin", name);
const targets = [
  { schema: "public", file: "packages/contracts/src/db.ts" },
  { schema: "demomart", file: "apps/demomart/lib/supabase/db.ts" },
];
const header =
  "// Generated by `pnpm db:types` from supabase/migrations. Do not edit by hand.\n";

function generate(schema, file) {
  const raw = execFileSync(
    bin("supabase"),
    ["gen", "types", "typescript", "--local", "--schema", schema],
    {
      cwd: root,
      encoding: "utf8",
      maxBuffer: 16 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    },
  );
  // Format through Biome so the committed file and a fresh generation compare byte for byte.
  return execFileSync(
    bin("biome"),
    ["format", `--stdin-file-path=${join(root, file)}`],
    { cwd: root, input: header + raw, encoding: "utf8" },
  );
}

const check = process.argv.includes("--check");
let stale = false;
for (const { schema, file } of targets) {
  const fresh = generate(schema, file);
  const path = join(root, file);
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {}
    if (current !== fresh) {
      console.error(`${file} is stale; run \`pnpm db:types\` and commit it.`);
      stale = true;
    }
  } else {
    writeFileSync(path, fresh);
    console.log(`wrote ${file} (${schema})`);
  }
}
process.exit(stale ? 1 : 0);
